#!/bin/bash
set -euxo pipefail

cd .build
docker-compose run --rm --service-ports --use-aliases odoo-server ./odoo/start-entrypoint.d/init-db
docker-compose run --rm --service-ports --use-aliases odoo-client ./odoo/start-entrypoint.d/init-db
