# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.1
_src_path: https://github.com/akretion/akretion-addons-repo-template.git
black_version: 20.8b1
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: '12.0'
prettify_xml: true
python_line_length: 88
rebel_module_groups: []
repo_description: Support
repo_name: Support
repo_slug: support
travis_apt_packages: []
travis_apt_sources: []
