version: "3.9"
services:
  postgres:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    image: postgres:13
    volumes:
      - db/:/var/lib/postgresql/data
  odoo-server:
    user: "${LOCAL_UID}:${LOCAL_UID}"
    environment:
      PGDATABASE: dbserver
      DEMO: "True"
      WORKERS: 0
      SERVER_WIDE_MODULES: web
      ADDITIONAL_ODOO_RC: |-
        encryption_key_dev=-Zlvw8hr_MHSkS8PLhDpQjtqYDZT-6npSgIeOGA8FUE=
    build:
      context: ..
      dockerfile: tools/Dockerfile
      args:
        VERSION: $SERVER_VERSION
        PYTHON_VERSION: 3.6
        MODULE: project_api
        LOCAL_UID: $LOCAL_UID
    depends_on:
      - postgres
    volumes:
      - odoo-server:/data/odoo
      - ../:/odoo/addons
  odoo-client:
    user: "${LOCAL_UID}:${LOCAL_UID}"
    environment:
      PGDATABASE: "dbclient_${CLIENT_VERSION}"
      DEMO: "True"
      WORKERS: 0
      SERVER_WIDE_MODULES: web
      ADDITIONAL_ODOO_RC: |-
        encryption_key_dev=-Zlvw8hr_MHSkS8PLhDpQjtqYDZT-6npSgIeOGA8FUE=
    build:
      context: ..
      dockerfile: tools/Dockerfile
      args:
        VERSION: $CLIENT_VERSION
        PYTHON_VERSION: $CLIENT_PYTHON_VERSION
        MODULE: project_api_client
        LOCAL_UID: $LOCAL_UID
    depends_on:
      - postgres
    volumes:
      - odoo-client:/data/odoo
      - ../:/odoo/addons
volumes:
  odoo-server:
  odoo-client:
  db:
