version: "3.9"
services:
  postgres:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    image: postgres:13
    volumes:
      - .db/:/var/lib/postgresql/data
  odoo-server:
    environment:
      PGDATABASE: dbserver
      DEMO: "True"
      WORKERS: 0
      SERVER_WIDE_MODULES: web
      ADDITIONAL_ODOO_RC: |-
        encryption_key_dev=-Zlvw8hr_MHSkS8PLhDpQjtqYDZT-6npSgIeOGA8FUE=
    build:
      context: ..
      dockerfile: tools/Dockerfile
      args:
        VERSION: $SERVER_VERSION
        MODULE: project_api
    depends_on:
      - postgres
    volumes:
      - odoo-server:/data/odoo
  odoo-client:
    environment:
      PGDATABASE: dbclient
      DEMO: "True"
      WORKERS: 0
      SERVER_WIDE_MODULES: web
      ADDITIONAL_ODOO_RC: |-
        encryption_key_dev=-Zlvw8hr_MHSkS8PLhDpQjtqYDZT-6npSgIeOGA8FUE=
    build:
      context: ..
      dockerfile: tools/Dockerfile
      args:
        VERSION: $CLIENT_VERSION
        MODULE: project_api_client
    depends_on:
      - postgres
      - odoo-server
    volumes:
      - odoo-client:/data/odoo
volumes:
  odoo-server:
  odoo-client:
