name: test Odoo addons

on:
  pull_request:
    branches:
      - "14.0*"
  push:
    branches:
      - "14.0*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        server_version: ["12.0"]
        client_version: ["14.0"]
    env:
      SERVER_VERSION: ${{ matrix.server_version }}
      CLIENT_VERSION: ${{ matrix.client_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Build
        run: ./tools/build
      - name: Init Server Database
        run: ./tools/start-server init-db
      - name: Init Client Database
        run: ./tools/start-client init-db
      - name: Run Client Test
        run: ./tools/start-client run-test
      - uses: codecov/codecov-action@v2
