[project]
name = "odoo-addons-akretion-support"
version = "18.0.20260408.0"
dependencies = [
    "odoo-addon-support==18.0.*",
    "odoo-addon-support_akretion==18.0.*",
    "odoo-addon-support_server==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
